name: Générer un APK

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Décompresser le projet
        run: unzip -o projet.zip -d .

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Flutter Pub Get
        run: flutter pub get

      - name: Générer les icônes de l'application
        run: dart run flutter_launcher_icons

      - name: Compiler l'APK
        run: flutter build apk --release

      - uses: actions/upload-artifact@v4
        with:
          name: examen scolaire apk
          path: build/app/outputs/flutter-apk/app-release.apk
